### ISSUE TITLE
installing soccerwindow

### ISSUE THREAD

**Issue by shahabty** [RoboCup2D/tutorial#1]
when i want to make soccerwindow 5.1.0 on ubuntu 16.04 i faced with this error : 
g++: error: unrecognized command line option ‘-pthread-lQtGui’
Makefile:415: recipe for target 'soccerwindow2-qt4' failed
make[3]: *** [soccerwindow2-qt4] Error 1

Qt version 4.8.7
rcssserver and monitor are already installed
libscrc version 4.1.0
thanks

**Comment by herodrigues** [comment]
I'm not aware about this error, but it's probably due to your Qt version.

**Comment by drdeng** [comment]
I meet  same problem, I suggest use ubuntu14.04 to install

**Comment by drdeng** [comment]
g++: error: unrecognized command line option ‘-pthread-lQtGui’
may be there is reason

**Comment by drdeng** [comment]
I  slove this probleam ,  and  I  write  a  script  for  auto  install robocup 2d  platform (rcssever . rcssmonitor  .soccerwindow2  . fedit2 )  you can  see  this  project  [Robocup2dForUbuntu16.04](https://github.com/drdeng/Robocup2dForUbuntu16.04)

**Comment by herodrigues** [comment]
Hey, guys. I have plans for moving this repository to an organization named Robocup2D. Do you guys wish to join it?

**Comment by drdeng** [comment]
Yes,of course, It's my pleasure

**Comment by herodrigues** [comment]
@drdeng , just added you. Now you should be able to edit the repositories.

**Comment by herodrigues** [comment]
*Solution*

Open the configure file, locate the line below and put a space between $PKG_CONFIG the variables, so it will be like this:

```bash
QT4_LDADD="$($PKG_CONFIG --static --libs-only-other $QT4_REQUIRED_MODULES) $($PKG_CONFIG --static --libs-only-l $QT4_REQUIRED_MODULES)"
```

**Comment by drdeng** [comment]
see this project  , it may help you
https://github.com/drdeng/Robocup2dInstall

2017-03-13 21:46 GMT+08:00 Herinson <notifications@github.com>:
